In [54]:
#Carga de librerias
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
# carga de base de datos 
bookings = pd.read_csv("bookings_report_casas_sabro - Sheet1.csv")
bookings.head()

,Listing Name,Check-in Date,Check-out Date,Booked Date,Average Daily Rate,Rental Revenue,Total Revenue,Currency,Booking Source,Booking Status,...,Listing ID,Unit ID,PMS,Property Name,BR Count,Group,Sub-Group,Tags,City,Sync Price
0,OASIS PH - Hot Tub | 2 Terraces,25 abr 2026,09 may 2026,07 abr 2026,$ 103.39,"$ 1,447.50","$ 1,497.50",USD,Airbnb,Booked,...,f4eb04a3-fd3c-447f-8a01-31e260bbb89b,f4eb04a3-fd3c-447f-8a01-31e260bbb89b,Hospitable,NaN,2,NaN,NaN,NaN,Medellín,On
1,OASIS PH - Hot Tub | 2 Terraces,16 may 2026,16 jun 2026,19 mar 2026,$ 77.81,"$ 2,412.00","$ 2,462.00",USD,Airbnb,Booked,...,f4eb04a3-fd3c-447f-8a01-31e260bbb89b,f4eb04a3-fd3c-447f-8a01-31e260bbb89b,Hospitable,NaN,2,NaN,NaN,NaN,Medellín,On
2,OASIS 201 - Balcony | Tub | 500M,15 mar 2026,19 abr 2026,06 mar 2026,$ 41.66,"$ 1,458.00","$ 1,483.00",USD,Airbnb,Booked,...,9fa010e4-9b94-4b9b-b6de-1792596bb063,9fa010e4-9b94-4b9b-b6de-1792596bb063,Hospitable,NaN,1,NaN,NaN,NaN,Medellín,On
3,OASIS 201 - Balcony | Tub | 500M,13 feb 2026,13 mar 2026,08 feb 2026,$ 40.93,"$ 1,146.00","$ 1,171.00",USD,Airbnb,Booked,...,9fa010e4-9b94-4b9b-b6de-1792596bb063,9fa010e4-9b94-4b9b-b6de-1792596bb063,Hospitable,NaN,1,NaN,NaN,NaN,Medellín,On
4,OASIS PH - Hot Tub | 2 Terraces,12 mar 2026,23 abr 2026,08 feb 2026,$ 79.52,"$ 3,340.00","$ 3,390.00",USD,Airbnb,Booked,...,f4eb04a3-fd3c-447f-8a01-31e260bbb89b,f4eb04a3-fd3c-447f-8a01-31e260bbb89b,Hospitable,NaN,2,NaN,NaN,NaN,Medellín,On

In [56]:
#Limpieza y preparación de datos
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Listing Name           248 non-null    object
 1   Check-in Date          248 non-null    object
 2   Check-out Date         248 non-null    object
 3   Booked Date            248 non-null    object
 4   Average Daily Rate     248 non-null    object
 5   Rental Revenue         248 non-null    object
 6   Total Revenue          248 non-null    object
 7   Currency               248 non-null    object
 8   Booking Source         248 non-null    object
 9   Booking Status         248 non-null    object
 10  Length of Stay (Days)  248 non-null    int64
 11  Booking Window (Days)  248 non-null    int64
 12  Reservation ID         248 non-null    object
 13  Listing ID             248 non-null    object
 14  Unit ID                248 non-null    object
 15  PMS                    248 non-null    object
 16  Property Name          0 non-null      float64
 17  BR Count               248 non-null    int64
 18  Group                  0 non-null      float64
 19  Sub-Group              0 non-null      float64
 20  Tags                   0 non-null      float64
 21  City                   248 non-null    object
 22  Sync Price             248 non-null    object
dtypes: float64(4), int64(3), object(16)
memory usage: 44.7+ KB

In [57]:
# Eliminar columnas vacías
bookings = bookings.dropna(axis=1, how="all")

In [58]:
#Confirmar que se eliminaron las columnas vacías
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Listing Name           248 non-null    object
 1   Check-in Date          248 non-null    object
 2   Check-out Date         248 non-null    object
 3   Booked Date            248 non-null    object
 4   Average Daily Rate     248 non-null    object
 5   Rental Revenue         248 non-null    object
 6   Total Revenue          248 non-null    object
 7   Currency               248 non-null    object
 8   Booking Source         248 non-null    object
 9   Booking Status         248 non-null    object
 10  Length of Stay (Days)  248 non-null    int64
 11  Booking Window (Days)  248 non-null    int64
 12  Reservation ID         248 non-null    object
 13  Listing ID             248 non-null    object
 14  Unit ID                248 non-null    object
 15  PMS                    248 non-null    object
 16  BR Count               248 non-null    int64
 17  City                   248 non-null    object
 18  Sync Price             248 non-null    object
dtypes: int64(3), object(16)
memory usage: 36.9+ KB

In [59]:
#Transformación de los datos
#Cambiar el data type de las columnas numericas y de las columnas que contienen fechas 

money_cols = ["Average Daily Rate", "Rental Revenue", "Total Revenue"]
for col in money_cols:
    bookings[col] = bookings[col].astype(str).str.replace(r"[^\d.]", "", regex=True).astype(float)

In [60]:
#Cambiar el data type de las columnas que contienen fechas
date_cols = ["Check-in Date", "Check-out Date", "Booked Date"]
meses_es_en = {
    "ene": "Jan", "feb": "Feb", "mar": "Mar", "abr": "Apr",
    "may": "May", "jun": "Jun", "jul": "Jul", "ago": "Aug",
    "sep": "Sep", "oct": "Oct", "nov": "Nov", "dic": "Dec"
}
for col in date_cols:
    temp = bookings[col].astype(str).str.lower()
    for es, en in meses_es_en.items():
        temp = temp.str.replace(es, en, regex=False)
    bookings[col] = pd.to_datetime(temp, format="%d %b %Y", errors="coerce")

bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Listing Name           248 non-null    object
 1   Check-in Date          248 non-null    datetime64[ns]
 2   Check-out Date         248 non-null    datetime64[ns]
 3   Booked Date            248 non-null    datetime64[ns]
 4   Average Daily Rate     248 non-null    float64
 5   Rental Revenue         248 non-null    float64
 6   Total Revenue          248 non-null    float64
 7   Currency               248 non-null    object
 8   Booking Source         248 non-null    object
 9   Booking Status         248 non-null    object
 10  Length of Stay (Days)  248 non-null    int64
 11  Booking Window (Days)  248 non-null    int64
 12  Reservation ID         248 non-null    object
 13  Listing ID             248 non-null    object
 14  Unit ID                248 non-null    object
 15  PMS                    248 non-null    object
 16  BR Count               248 non-null    int64
 17  City                   248 non-null    object
 18  Sync Price             248 non-null    object
dtypes: datetime64[ns](3), float64(3), int64(3), object(10)
memory usage: 36.9+ KB

In [61]:
# Eliminar filas sin fecha válida ────────────────────
bookings = bookings.dropna(subset=["Check-in Date"]).copy()
print(f"Registros válidos: {len(bookings)} de 248")

Registros válidos: 248 de 248

In [40]:
# Gaps entre reservas por propiedad
bookings = bookings.sort_values(["Listing ID", "Booked Date"])
bookings["prev_booked"]      = bookings.groupby("Listing ID")["Booked Date"].shift(1)
bookings["days_since_last"]  = (bookings["Booked Date"] - bookings["prev_booked"]).dt.days

# Flags
bookings["flag_last_minute"] = bookings["Booking Window (Days)"] <= 15
bookings["flag_orphan"]      = bookings["Length of Stay (Days)"].between(1, 9) & bookings["Booking Window (Days)"].between(0, 30)
bookings["flag_recency"]     = bookings["days_since_last"] >= 15
bookings["flag_discount"]    = bookings["flag_last_minute"] | bookings["flag_orphan"] | bookings["flag_recency"]

print(f"Total reservas: {len(bookings)}")
print(f"Con descuento:  {bookings['flag_discount'].sum()} ({bookings['flag_discount'].mean():.1%})")

Total reservas: 248
Con descuento:  215 (86.7%)

In [64]:
bookings["Año"]     = bookings["Check-in Date"].dt.year.astype(int)
bookings["Mes_num"] = bookings["Check-in Date"].dt.month
bookings["BW_calc"] = (bookings["Check-in Date"] - bookings["Booked Date"]).dt.days

bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Listing Name           248 non-null    object
 1   Check-in Date          248 non-null    datetime64[ns]
 2   Check-out Date         248 non-null    datetime64[ns]
 3   Booked Date            248 non-null    datetime64[ns]
 4   Average Daily Rate     248 non-null    float64
 5   Rental Revenue         248 non-null    float64
 6   Total Revenue          248 non-null    float64
 7   Currency               248 non-null    object
 8   Booking Source         248 non-null    object
 9   Booking Status         248 non-null    object
 10  Length of Stay (Days)  248 non-null    int64
 11  Booking Window (Days)  248 non-null    int64
 12  Reservation ID         248 non-null    object
 13  Listing ID             248 non-null    object
 14  Unit ID                248 non-null    object
 15  PMS                    248 non-null    object
 16  BR Count               248 non-null    int64
 17  City                   248 non-null    object
 18  Sync Price             248 non-null    object
 19  Año                    248 non-null    int64
 20  Mes_num                248 non-null    int32
 21  BW_calc                248 non-null    int64
dtypes: datetime64[ns](3), float64(3), int32(1), int64(5), object(10)
memory usage: 41.8+ KB

In [66]:
#Suposición de lo que se fuese ganado si no se hubiesen aplicado descuentos
#Last Minute: 30% de descuento
#Orphan: 20% de descuento
#Recency: 10% de descuento (Promedio, entre 5% y 15%)
bookings = bookings.sort_values(["Listing ID", "Booked Date"])
bookings["prev_booked"]     = bookings.groupby("Listing ID")["Booked Date"].shift(1)
bookings["days_since_last"] = (bookings["Booked Date"] - bookings["prev_booked"]).dt.days

# Flags
bookings["flag_last_minute"] = bookings["Booking Window (Days)"] <= 15
bookings["flag_orphan"]      = bookings["Length of Stay (Days)"].between(1, 9) & bookings["Booking Window (Days)"].between(0, 30)
bookings["flag_recency"]     = bookings["days_since_last"] >= 30
bookings["flag_discount"]    = bookings["flag_last_minute"] | bookings["flag_orphan"] | bookings["flag_recency"]

print(f"Total reservas: {len(bookings)}")
print(f"Con descuento:  {bookings['flag_discount'].sum()} ({bookings['flag_discount'].mean():.1%})")

Total reservas: 248
Con descuento:  210 (84.7%)

In [67]:
#Validar que las flags funcionan correctamente
print("Last minute:", bookings["flag_last_minute"].sum())
print("Orphan:",      bookings["flag_orphan"].sum())
print("Recency:",     bookings["flag_recency"].sum())
print("Total con descuento:", bookings["flag_discount"].sum())

Last minute: 189
Orphan: 78
Recency: 84
Total con descuento: 210

In [73]:
print(bookings.columns.tolist())

['Listing Name', 'Check-in Date', 'Check-out Date', 'Booked Date', 'Average Daily Rate', 'Rental Revenue', 'Total Revenue', 'Currency', 'Booking Source', 'Booking Status', 'Length of Stay (Days)', 'Booking Window (Days)', 'Reservation ID', 'Listing ID', 'Unit ID', 'PMS', 'BR Count', 'City', 'Sync Price', 'Año', 'Mes_num', 'BW_calc', 'prev_booked', 'days_since_last', 'flag_last_minute', 'flag_orphan', 'flag_recency', 'flag_discount']

In [74]:
def adr_ideal(row):
    if row["flag_last_minute"]: return row["Average Daily Rate"] / 0.70
    if row["flag_orphan"]:      return row["Average Daily Rate"] / 0.80
    if row["flag_recency"]:     return row["Average Daily Rate"] / 0.90
    return row["Average Daily Rate"]

bookings["ADR_ideal"]       = bookings.apply(adr_ideal, axis=1)
bookings["Revenue_ideal"]   = bookings["ADR_ideal"] * bookings["Length of Stay (Days)"]
bookings["Revenue_perdido"] = bookings["Revenue_ideal"] - bookings["Total Revenue"]

# Verificar que se crearon
print(bookings[["Average Daily Rate", "ADR_ideal", "Revenue_ideal", "Revenue_perdido"]].head())

     Average Daily Rate  ADR_ideal  Revenue_ideal  Revenue_perdido
244               42.00  42.000000      84.000000         0.000000
243               13.81  19.728571     532.671429       159.671429
238               24.40  34.857143     174.285714        52.285714
235               25.67  36.671429     110.014286        33.014286
232               22.14  31.628571     221.400000        66.400000

In [75]:
#Ganancia total vs ganancia ideal
revenue_real     = bookings["Total Revenue"].sum()
revenue_ideal    = bookings["Revenue_ideal"].sum()
revenue_perdido  = revenue_ideal - revenue_real

print(f" Revenue real: ${revenue_real:,.0f}")
print(f" Revenue ideal: ${revenue_ideal:,.0f}")
print(f" Revenue lost: ${revenue_perdido:,.0f}")

# Porcentaje de ganancia perdida con descuento 
pct_perdido      = revenue_perdido / revenue_ideal
print(f" Lost: {pct_perdido:.1%}")

 Revenue real: $159,571
 Revenue ideal: $192,011
 Revenue lost: $32,441
 Lost: 16.9%

In [78]:
print(f"Desde: {bookings['Check-in Date'].min().date()}")
print(f"Hasta: {bookings['Check-in Date'].max().date()}")
print(f"Años disponibles: {sorted(bookings['Check-in Date'].dt.year.unique())}")

Desde: 2022-09-25
Hasta: 2026-05-16
Años disponibles: [np.int32(2022), np.int32(2023), np.int32(2024), np.int32(2025), np.int32(2026)]

In [77]:
bookings = bookings.dropna(subset=["Check-in Date"])
print(f"Registros después de limpiar fechas: {len(bookings)}")

Registros después de limpiar fechas: 248

In [79]:
#Ganancias por año
#En el año 2026 es hasta el mes de abril, mes en donde hacemos el analisis 
#Hay que tener en cuenta que las ganacias en ese año pueden ser menores por esto, y no necesariamente por una disminución en las reservas o en el precio promedio.
#Ademas, se debe tener en cuenta que desde finales de 2025 Casa vip dejo de operar sus 6 habiatciones 
bookings["Año"] = bookings["Check-in Date"].dt.year

# Resumen anual
anual = bookings.groupby("Año").agg(
    reservas        = ("Reservation ID", "count"),
    revenue_real    = ("Total Revenue", "sum"),
    revenue_ideal   = ("Revenue_ideal", "sum"),
).reset_index()

anual["revenue_perdido"] = anual["revenue_ideal"] - anual["revenue_real"]
anual["pct_perdido"]     = (anual["revenue_perdido"] / anual["revenue_ideal"] * 100).round(1)

# Formatear valores para lectura
anual_display = anual.copy()
for col in ["revenue_real", "revenue_ideal", "revenue_perdido"]:
    anual_display[col] = anual_display[col].map("${:,.0f}".format)
anual_display["pct_perdido"] = anual_display["pct_perdido"].map("{}%".format)

anual_display

    Año  reservas revenue_real revenue_ideal revenue_perdido pct_perdido
0  2022        18       $3,284        $4,655          $1,371       29.5%
1  2023        59      $25,390       $31,114          $5,723       18.4%
2  2024        72      $59,311       $73,108         $13,797       18.9%
3  2025        90      $56,529       $64,713          $8,184       12.6%
4  2026         9      $15,056       $18,422          $3,366       18.3%

In [81]:
print(len(bookings))

248